version: '3'

services:
  catchbadmintoncourt:
    image: catchbadmintoncourt
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file:
      - ./.env
